# Generated by Django 4.1.7 on 2023-12-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_hobby_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobbyfsctor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(max_length=20)),
                ('hobbyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.hobby_table')),
            ],
        ),
    ]
