# Generated by Django 4.1.7 on 2023-12-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_hobbyfsctor_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hobbyfsctor_table',
            new_name='hobbyfactor_table',
        ),
    ]
