# Generated by Django 4.1.7 on 2023-12-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0004_rename_hobbyfsctor_table_hobbyfactor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='season_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=20)),
            ],
        ),
    ]
