# Generated by Django 4.1.7 on 2023-12-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0005_season_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='season_factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(max_length=20)),
                ('seasonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.season_table')),
            ],
        ),
    ]
