# Generated by Django 4.1.7 on 2023-12-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0006_season_factor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='season_factor',
            new_name='seasonfactor_table',
        ),
    ]
