# Generated by Django 4.1.7 on 2023-12-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_hobbie_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('filterstatus', models.CharField(default='pending', max_length=20)),
                ('reciverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciverid', to='user.register_table')),
                ('senderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderid', to='user.register_table')),
            ],
        ),
    ]
